# Generated by Django 5.1.5 on 2025-11-02 19:46

import apps.proagua_api.models.solicitacao
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='media/images')),
                ('description', models.TextField(max_length=250, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temperatura', models.FloatField(blank=True, default=9.5, null=True, verbose_name='temperatura mínima')),
                ('max_temperatura', models.FloatField(blank=True, default=10.5, null=True, verbose_name='temperatura máxima')),
                ('min_cloro_residual_livre', models.FloatField(blank=True, default=0.2, null=True, verbose_name='cloro residual livre mínimo')),
                ('max_cloro_residual_livre', models.FloatField(blank=True, default=5.0, null=True, verbose_name='cloro residual livre máximo')),
                ('min_turbidez', models.FloatField(blank=True, default=None, null=True, verbose_name='turbidez mínima')),
                ('max_turbidez', models.FloatField(blank=True, default=5.0, null=True, verbose_name='turbidez máxima')),
                ('coliformes_totais', models.BooleanField(default=False, verbose_name='coliformes totais')),
                ('escherichia', models.BooleanField(default=False, verbose_name='escherichia coli')),
            ],
        ),
        migrations.CreateModel(
            name='Edificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('campus', models.CharField(choices=[('LE', 'Leste'), ('OE', 'Oeste')], default=('LE', 'Leste'), max_length=2, verbose_name='campus')),
                ('cronograma', models.PositiveIntegerField(verbose_name='cronograma')),
                ('imagens', models.ManyToManyField(to='proagua_api.image')),
            ],
        ),
        migrations.CreateModel(
            name='PontoColeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ambiente', models.CharField(max_length=20, verbose_name='ambiente')),
                ('tipo', models.IntegerField(choices=[(1, 'Bebedouro'), (2, 'Reservatório predial superior'), (3, 'Reservatório predial inferior'), (4, 'Reservatório de distribuição superior'), (5, 'Reservatório de distribuição inferior'), (6, 'CAERN')], default=(1, 'Bebedouro'), verbose_name='tipo')),
                ('tombo', models.CharField(blank=True, max_length=20, null=True, verbose_name='tombo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media/images/edificacoes')),
                ('amontante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ponto_amontante', to='proagua_api.pontocoleta', verbose_name='ponto amontante')),
                ('associados', models.ManyToManyField(blank=True, null=True, related_name='ponto_associado', to='proagua_api.pontocoleta', verbose_name='reservatorios associados')),
                ('edificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PontoColeta', to='proagua_api.edificacao', verbose_name='código da edificação')),
            ],
        ),
        migrations.CreateModel(
            name='Fluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.ManyToManyField(to='proagua_api.pontocoleta')),
            ],
        ),
        migrations.CreateModel(
            name='SequenciaColetas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amostragem', models.PositiveIntegerField(verbose_name='amostragem')),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proagua_api.pontocoleta', verbose_name='ponto')),
            ],
            options={
                'unique_together': {('amostragem', 'ponto')},
            },
        ),
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperatura', models.FloatField(verbose_name='temperatura')),
                ('cloro_residual_livre', models.FloatField(verbose_name='cloro residual livre')),
                ('turbidez', models.FloatField(verbose_name='turbidez')),
                ('coliformes_totais', models.BooleanField(verbose_name='coliformes totais')),
                ('escherichia', models.BooleanField(verbose_name='escherichia coli')),
                ('cor', models.FloatField(verbose_name='cor')),
                ('data', models.DateTimeField(verbose_name='data da coleta')),
                ('ordem', models.CharField(choices=[('C', 'Coleta'), ('R', 'Recoleta')], default=('C', 'Coleta'), max_length=1)),
                ('status', models.BooleanField(default=None, null=True, verbose_name='status')),
                ('status_message', models.CharField(default=None, max_length=200, null=True, verbose_name='status message')),
                ('responsavel', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='responsaveis')),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coletas', to='proagua_api.pontocoleta', verbose_name='Ponto de Coleta')),
                ('sequencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coletas', to='proagua_api.sequenciacoletas', verbose_name='sequência de Coletas')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data da solicitação')),
                ('objetivo', models.TextField(blank=True, max_length=1250, null=True, verbose_name='objetivo da solicitação')),
                ('justificativa', models.TextField(blank=True, max_length=1250, null=True, verbose_name='justificativa da solicitação')),
                ('tipo', models.CharField(choices=[('Limpeza de reservatório', 'Limpeza de reservatório'), ('Instalação de ponto de coleta', 'Instalação de ponto de coleta'), ('Conserto de reservatório', 'Conserto de reservatório')], default='Limpeza de reservatório', max_length=50, verbose_name='tipo de solicitação')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Concluido', 'Concluido')], default=apps.proagua_api.models.solicitacao.Status['PENDENTE'], max_length=50, verbose_name='status')),
                ('imagens', models.ManyToManyField(to='proagua_api.image')),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Solicitacao', to='proagua_api.pontocoleta', verbose_name='ponto de coleta')),
            ],
        ),
    ]
