services:
  backend:
    container_name: "proagua-backend"
    build: .
    ports:
      - 8000:8000
    networks:
      - mynet
    depends_on:
      - database
  
  database:
    container_name: "proagua-db"
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
