# Generated by Django 5.1.3 on 2024-12-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proagua_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosreferencia',
            name='max_cor',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='cor máxima'),
        ),
        migrations.AddField(
            model_name='parametrosreferencia',
            name='min_cor',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='cor mínima'),
        ),
        migrations.AlterField(
            model_name='coleta',
            name='ordem',
            field=models.CharField(choices=[('C', 'Coleta'), ('R', 'Recoleta')], default=('C', 'Coleta'), max_length=8),
        ),
    ]
