# Generated by Django 5.1.5 on 2025-03-27 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proagua_api', '0002_parametrosreferencia_max_cor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleta',
            name='ordem',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
