# Generated by Django 5.1.5 on 2025-05-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proagua_api', '0003_alter_coleta_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleta',
            name='publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pontocoleta',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Bebedouro'), (1, 'Torneira'), (2, 'Reservatório predial superior'), (3, 'Reservatório predial inferior'), (4, 'Reservatório de distribuição superior'), (5, 'Reservatório de distribuição inferior'), (6, 'CAERN')], default=(0, 'Bebedouro'), verbose_name='tipo'),
        ),
    ]
