# Generated by Django 5.1.5 on 2025-05-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proagua_api', '0006_alter_coleta_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleta',
            name='publico',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
